apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager-metrics
  labels:
    control-plane: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/name: connection-operator
    control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.metricsService.ports | toYaml | nindent 2 }}
